### ISSUE TITLE
Solicitud : Crear un nuevo Mob Neutral (Caballo)

### ISSUE THREAD

**Issue by pieroHerreraT** [Team-Software/Minecraft-mods#3]
El Mod actual posee items con usos específicos; sin embargo, aun no ha sido agregado ningún Mob (entidades vivientes del juego). Los mobs neutrales  pueden o no representar un peligro para el jugador. Se agregará el mob neutral denominado **Adamantium Horse**, que seguirá con la temática del Mod.

**Comment by TrynowPht** [comment]
Comenzamos con la creación de EntityInit. Esta es la clase padre que incluirá los métodos que permiten registrar cualquier mob (entidad) que queramos introducir en el juego.

`public class EntityInit {

	public static void registerEntities() {
		registerEntity("AdamantiumHorse", EntityAdamantiumHorse.class, Reference.ENTITY_ADAMANTIUMHORSE, 120, 58111, 2149);
	}
	private static void registerEntity(String name, Class <? extends Entity> entity, int id, int range, int color1, int color2) {
		EntityRegistry.registerModEntity(new ResourceLocation(Reference.MOD_ID + ":" + name), entity, name, id, Main.instance, range, 1, true, color1, color2);
	}
}`

**Comment by pieroHerreraT** [comment]
Como primer paso se procederá a crear una nueva clase llamada **_EntityInit.java_** dentro del paquete init. Esta es una clase padre que contendrá los métodos que permitirán registrar cualquier mob (entidad) que se deseea agregar posteriormente al juego.
Localización de clases necesarias para su implementación : 

```
import net.minecraft.entity.Entity; //Clase de entidades de Minecraft
import net.minecraftforge.fml.common.registry.EntityRegistry; // Importamos la clase de registro para los atributos del generador de entidad (egg spawner)

```

```
public class EntityInit{

	public static void registerEntities(){
		registerEntity("AdamantiumHorse", EntityAdamantiumHorse.class, Reference.ENTITY_ADAMANTIUMHORSE, 120, 58111, 2149);
	}
	
	private static void registerEntity(String name, Class <? extends Entity> entity, int id, int range, int color1, int color2){
		EntityRegistry.registerModEntity(new ResourceLocation(Reference.MOD_ID + ":" + name), entity, name, id, Main.instance, range, 1, true, color1, color2);
	}
}

```

**Comment by pieroHerreraT** [comment]
Para referir a una entidad se necesita otorgarle una ID. Localización de problema: Se actualiza la clase **_Reference.java_** añadiendo el ID de referencia que tendrá el Mob:

```
public static final int ENTITY_ADAMANTIUMHORSE = 120;
```

**Comment by pieroHerreraT** [comment]
Existe un problema y es que no se tiene una función que permita iniciar las entidades registradas al crear un mundo en el juego (partida nueva). Localización: Clase _**RegistryHandler.java**_ 
Para esto se añadió en la clase _RegistryHandler_ el siguiente método
```
public static void preInitRegistries() {
		EntityInit.registerEntities();  //método de registro de entidades
	}
```

**Comment by pieroHerreraT** [comment]
Necesitamos crear una clase que contenga los atributos y características que queremos que tenga el mob. Es por esto que debemos de crear la clase **EntityAdamantiumHorse**.  Esta se encontrará dentro del nuevo paquete creado en `com.trynow.adamod` llamad **entity**

**Comment by pieroHerreraT** [comment]
Ya que el mob que queremos crear es un caballo, este se puede derivar de cualquiera de las clases de caballos existentes en el juego: Horse, SkeletonHorse y ZombieHorse. 
Por el momento la clase **EntityAdamantiumHorse** será una extensión de la clase **_EntitySkeletonHorse.java_**

```
public class EntityAdamantiumHorse extends EntitySkeletonHorse{ 
...
...
}
```

Aprovecharemos esto para incluir las características de AI, atributos y sonidos propios del mob.

**Comment by pieroHerreraT** [comment]
Se añade la generación en cualquier mundo creado

```
public EntityAdamantiumHorse(World worldIn) {
		super(worldIn); 
	}
	
```

**Comment by pieroHerreraT** [comment]
Localizamos que las características de Inteligencia Artificial se encuentran en **_EntityHorse_** la cual se ubica en `net -> minecraft -> entity -> passive ->EntityHorse`

Las principales características de AI que poseen los caballos son:
```
- EntityAISwimming
- EntityAIPanic
- EntityAIRunAroundLikeCrazy
- EntityAIMate
- EntityAIFollowParent
- EntityAIWanderAvoidWater
- EntityAIWatchClosest
- EntityAILookIdle
```

Tener en cuenta que _EntityHorse_ es una extensión de otra clase llamada _**AbstractHorse**_ que contiene todos los tipos de caballos.

**Comment by pieroHerreraT** [comment]
De _**EntitySkeletonHorse**_  obtenemos los métodos que sirven para obtener los sonidos de ambiente, daño y muerte. Además de los atributos como vida, velocidad y salto.
Todos estos métodos los incluimos en nuestra clase _**EntityAdamantiumHorse**_

**Comment by pieroHerreraT** [comment]
Los mobs necesitan ser generados a través de un modelado 3D del propio juego. Esto se le conoce como Render. Para permitir de que el juego procese el render del mob debemos de registrarlo. 
Localizamos las clases que permiten realizar estas acciones:
```
net -> minecraft -> client -> renderer -> entity -> Render
net -> minecraft -> client -> renderer -> entity -> RenderManager

net -> minecraftforge -> fml -> client -> registry -> IRenderFactory
*net -> minecraftforge -> fml -> client -> registry -> RenderingRegistry

*net -> minecraft -> client -> renderer -> entity -> RenderLiving

```
Por eso creamos dos nuevas clases:
_**RenderHandlers**_: Incluye el método que permite registrar cualquier render de entidades
_**RenderAdamantiumHorse**_ : Clase que incluye el render del mob en específico. Posee los metodos para identificar las texturas en formato png, así como también el método que permite crear el egg spawner (item para la generación del mob). Se encuentra dentro de un nuevo paquete llamado **_render_**, creado dentro del paquete _entity_.

**Comment by pieroHerreraT** [comment]
Añadimos el método _**registerEntityRenders()**_ en la clase **_RegistryHandler_**, pues también requiere de su inicialización. Va a ir dentro del método _preInitRegistries_ creado anteriormente

**Comment by pieroHerreraT** [comment]
Para la creación del modelado 3D y de las texturas es necesario el uso de dos Mods: **Tabula** y **IChuntil**.
Se procede a realizar la descargar de sus instaladores correspondientes. Para utilizar los mods es necesario tener instalado el juego y el forge correspondiente. Aparecerá un botón con la letra _**T**_ que permitirá acceder a las características deseadas.

**Comment by pieroHerreraT** [comment]
Hubo problemas debido a que la versión del forge en la que se estaba realizando el desarrollo del programa no era compatible con las versiones de estos mods.

**Comment by pieroHerreraT** [comment]
Se logró solucionar el problema de compatibilidad. Se realizó una importación de las texturas del SkeletonHorse. Se crea el modelado 3D a partir de las texturas propias que nos brinda el juego.

**Comment by pieroHerreraT** [comment]
Se debe de crear un nuevo paquete dentro del paquete entity llamado **_model_**. Exportamos el mob creado como una clase de java. 
Se coloca la siguiente dirección:
`com -> trynow -> adamod -> entity -> model`
y de nombre _**ModelAdamantiumHorse**_. 
También se exporta las texturas en formato png.

**Comment by pieroHerreraT** [comment]
Para acceder al código de la clase exportada debemos ingresar a la siguiente dirección:
` %appdata% -> .minecraft -> mods -> tabula -> export`
Copiamos el archivo .java y lo pegamos en nuestro paquete **_model_**

**Comment by pieroHerreraT** [comment]
El archivo png de las texturas también se encuentra en la misma dirección mencionada anteriormente. Se realizó un _**recoloreado**_ de las texturas exportadas del AdamantiumHorse.

**Comment by pieroHerreraT** [comment]
Para finalizar con la solicitud, creamos una nueva carpeta en la siguiente dirección:
`src -> main -> resources -> assets -> am ->textures`
con el nombre de entity. En esta carpeta se pega el archivo de las texturas con su nombre correspondiente. Tener en cuenta que el nombre debe ser el mismo que ingresamos en la clase **_RenderAdamantiumHorse_**, por el contrario no será reconocido.

**Comment by pieroHerreraT** [comment]
De esta forma damos por finalizada la solicitud de creación del mob AdamantiumHorse.
